name: Deploy DNS Bot

on:
  push:
    branches: [master]

permissions:
  contents: read
  id-token: write

cache-mode: none

jobs:
  deploy:
    uses: yearn/yearn-gha/.github/workflows/cloudflare-deploy.yml@e6b4d914d9256b6becdf7c30605238894fa54638
    with:
      project: dns-bot
      identity-id: ${{ vars.DOPPLER_PRODUCTION_IDENTITY_ID }}
